
# Site settings
title: H.E.L.M
banner: "Huellas en la Montaña"
description: >
  Somos una organización sin animo de lucro que protege y defiende el bienestar animal,
  formada por varios jóvenes que creemos que se puede luchar contra el maltrato animal.
baseurl: "/test"
url: "http://huellasweb.org"

# google_analytics: "test-analytics"

# Contact settings
email:
  adopciones: adopciones@huellasweb.org
  acogidas: acogidas@huellasweb.org
  eventos: eventos@huellasweb.org
  voluntarios: voluntarios@huellasweb.org
  donaciones: donaciones@huellasweb.org
  fotos: fotos@huellasweb.org
  consultas: contacto@huellasweb.org

# Main Nav settings
main-nav:
  Home: /about/
  Colabora: /colabora/
  Perros: /perros/
  Blog: /blog/
  Adoptados: /adoptados/
  Contacto: /contacto/

# Sub Navs settings
about-nav:
  Miembros: /about/miembros/
  Voluntarios: /about/voluntarios/
  Socios: /about/socios/

colabora-nav:
  Donativos: /colabora/donativos/
  Donaciones: /colabora/donaciones/
  Hazte Voluntario: /colabora/voluntarios/
  Hazte Socio: /colabora/socios/

perros-nav:
  Adoptar: /perros/adoptar/
  Apadrinar: /perros/apadrinar/
  Acoger: /perros/acoger/

blog-nav:
  Eventos: /blog/eventos/
  Articulos: /blog/articulos/

# Sub Nav Levels Adoptar/Apadrinar
adoptar-nav:
  Razas: /perros/adoptar/razas/
  Tamaño: /perros/adoptar/tallas/
  Sexo: /perros/adoptar/sexo/

apadrinar-nav:
  Razas: /perros/apadrinar/razas/
  Tamaño: /perros/apadrinar/tallas/
  Sexo: /perros/apadrinar/sexo/

# Collections settings
collections:
  posts:
    permalink: /blog/posts/:title/
  perros:
    output: true
    permalink: /perros/:path/
  galerias:
    output: true
    permalink: /perros/galerias/:path/

# Defaults settings
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: perros
    values:
      layout: perros
      order: 99
  - scope:
      path: ""
      type: galerias
    values:
      layout: default

# Build settings
markdown: kramdown
kramdown:
  input: GFM

#theme: minima
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
