
# Site settings
title: H.E.L.M
banner: "Huellas en la Montaña"
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""

# Contact settings
email: helm@domain.com

# Main Nav settings
main-nav:
  Home: /about/
  Colabora: /colabora/
  Perros: /perros/
  Blog: /blog/
  Adoptados Felizes: /adoptados/
  #Tienda: /tienda/

# Sub Navs settings
about-nav:
  Miembros: /about/miembros/
  Voluntarios: /about/voluntarios/
  Socios: /about/socios/

colabora-nav:
  Donativos: /colabora/donativos/
  Donaciones: /colabora/donaciones/
  Hazte Voluntario: /colabora/voluntarios/
  Hazte Socio: /colabora/socios/

perros-nav:
  Adoptar: /perros/adoptar/
  Apadrinar: /perros/apadrinar/
  Acoger: /perros/acoger/

blog-nav:
  Eventos: /blog/eventos/
  Articulos: /blog/articulos/

# Sub Nav Levels Adoptar/Apadrinar
adoptar-nav:
  Razas: /perros/adoptar/razas/
  Tamaño: /perros/adoptar/tallas/
  Sexo: /perros/adoptar/sexo/

apadrinar-nav:
  Razas: /perros/apadrinar/razas/
  Tamaño: /perros/apadrinar/tallas/
  Sexo: /perros/apadrinar/sexo/

# Collections settings
collections:
  posts:
    permalink: /blog/posts/:title/
  perros:
    output: true
    permalink: /perros/:path/
  galerias:
    output: true
    permalink: /perros/galerias/:path/

# Defaults settings
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: perros
    values:
      layout: perros
      order: 99
  - scope:
      path: ""
      type: galerias
    values:
      layout: default

# Build settings
markdown: kramdown
kramdown:
  input: GFM

#theme: minima
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
